from typing import Optional
from fastapi import HTTPException, status
from src.config import database
from src.models.user import UserCreate, UserInDB
from src.utils.security import get_password_hash, verify_password, create_access_token
from bson import ObjectId

class AuthService:
    @staticmethod
    async def get_user_by_email(email: str) -> Optional[dict]:
        user = await database.db.users.find_one({"email": email})
        return user

    @staticmethod
    async def create_user(user_data: UserCreate) -> dict:
        existing_user = await AuthService.get_user_by_email(user_data.email)
        if existing_user:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Email already registered"
            )

        hashed_password = get_password_hash(user_data.password)
        db_user = UserInDB(
            **user_data.model_dump(exclude={"password"}),
            password_hash=hashed_password
        )
        
        user_dict = db_user.model_dump(by_alias=True)
        # remove the generated _id to let mongo create it if we wanted, 
        # or we just use the one generated by model_dump. We'll use the generated one as an ObjectId
        user_dict["_id"] = ObjectId()
        
        result = await database.db.users.insert_one(user_dict)
        user_dict["_id"] = str(result.inserted_id)
        return user_dict

    @staticmethod
    async def authenticate_user(email: str, password: str) -> str:
        user = await AuthService.get_user_by_email(email)
        if not user:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Incorrect email or password",
                headers={"WWW-Authenticate": "Bearer"},
            )
            
        if not verify_password(password, user["password_hash"]):
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Incorrect email or password",
                headers={"WWW-Authenticate": "Bearer"},
            )
            
        access_token = create_access_token(data={"sub": user["email"]})
        return access_token, user
